# Generated by Django 4.2.8 on 2025-05-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxh', '0004_remove_notification_image_url_notification_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
