# Generated by Django 4.2.8 on 2025-05-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxh', '0005_remove_post_avatar_url_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='avatar_url',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
