# Generated by Django 4.2.8 on 2025-05-21 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mxh', '0007_notification_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='post',
        ),
    ]
