# Generated by Django 4.2.8 on 2025-05-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxh', '0010_alter_usernotification_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
